### ISSUE TITLE
chat commands

### ISSUE THREAD

**Issue by KangaRoo1372** [pilaf/webliero-faq#3]
1) there is one more chat command in webliero: /extrapolation. This one works similar as in Haxball ("Causes the game to extrapolate by a certain amount of milliseconds. It can be used to counteract the effects of input delay but at the cost of extra "warping" in the game prediction. It is recommended to leave this at 0 unless you have input delay"). In webliero, extrapolation must be a value between -200 and 200 milliseconds.

2) I would add some info in the description regarding /handicap command, i.e. info that ping handicap must be a value between 0 and 300 milliseconds (so maximum value is 300).

**Comment by pilaf** [comment]
Done 👍
